name: provider_with_mobx
description: Gives providing mobx store with provider.
version: 0.0.1
author: Ha Jae
homepage: https://rntlqvnf.github.io/
repository: https://github.com/rntlqvnf/provider_with_mobx

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
